import { NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { db } from "@/lib/db"
import { evaluateSubmissionWithByok } from "@/services/aiGradingService"

export async function POST(req) {
  try {
    const session = await auth()
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const role = session.user.role
    if (role !== "ADMIN" && role !== "OWNER") {
      return NextResponse.json({ error: "Forbidden: Admin access required" }, { status: 403 })
    }

    const body = await req.json()
    const { assignmentId, action } = body

    if (!assignmentId || !action) {
      return NextResponse.json({ error: "assignmentId and action are required" }, { status: 400 })
    }

    if (action === "AI_DRAFT_ALL") {
      const submissions = await db.submission.findMany({
        where: { assignmentId, deletedAt: null },
      })

      let count = 0
      for (const sub of submissions) {
        await evaluateSubmissionWithByok(sub.id)
        count++
      }

      return NextResponse.json({
        success: true,
        message: `Successfully generated BYOK AI draft scores for ${count} submissions!`,
        count,
      })
    }

    if (action === "PUBLISH_ALL") {
      const updated = await db.submission.updateMany({
        where: {
          assignmentId,
          deletedAt: null,
          status: "GRADED",
        },
        data: {
          isGradePublished: true,
        },
      })

      return NextResponse.json({
        success: true,
        message: `Successfully published grades for ${updated.count} evaluated submissions!`,
        count: updated.count,
      })
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 })
  } catch (error) {
    console.error("POST /api/admin/submissions/batch error:", error)
    return NextResponse.json({ error: error.message || "Failed to process batch action" }, { status: 500 })
  }
}
